repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: ruff
        language: python
        types: [python]
        args: ["--fix", "--show-fixes", "--exit-non-zero-on-fix"]